// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: market/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetMarketItemRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetMarketItemRequest) Reset()         { *m = QueryGetMarketItemRequest{} }
func (m *QueryGetMarketItemRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMarketItemRequest) ProtoMessage()    {}
func (*QueryGetMarketItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4839d34748ebb1, []int{0}
}
func (m *QueryGetMarketItemRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMarketItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMarketItemRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMarketItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMarketItemRequest.Merge(m, src)
}
func (m *QueryGetMarketItemRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMarketItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMarketItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMarketItemRequest proto.InternalMessageInfo

func (m *QueryGetMarketItemRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetMarketItemResponse struct {
	MarketItem MarketItem `protobuf:"bytes,1,opt,name=MarketItem,proto3" json:"MarketItem"`
}

func (m *QueryGetMarketItemResponse) Reset()         { *m = QueryGetMarketItemResponse{} }
func (m *QueryGetMarketItemResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMarketItemResponse) ProtoMessage()    {}
func (*QueryGetMarketItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4839d34748ebb1, []int{1}
}
func (m *QueryGetMarketItemResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMarketItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMarketItemResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMarketItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMarketItemResponse.Merge(m, src)
}
func (m *QueryGetMarketItemResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMarketItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMarketItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMarketItemResponse proto.InternalMessageInfo

func (m *QueryGetMarketItemResponse) GetMarketItem() MarketItem {
	if m != nil {
		return m.MarketItem
	}
	return MarketItem{}
}

type QueryAllMarketItemRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMarketItemRequest) Reset()         { *m = QueryAllMarketItemRequest{} }
func (m *QueryAllMarketItemRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllMarketItemRequest) ProtoMessage()    {}
func (*QueryAllMarketItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4839d34748ebb1, []int{2}
}
func (m *QueryAllMarketItemRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMarketItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMarketItemRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMarketItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMarketItemRequest.Merge(m, src)
}
func (m *QueryAllMarketItemRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMarketItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMarketItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMarketItemRequest proto.InternalMessageInfo

func (m *QueryAllMarketItemRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllMarketItemResponse struct {
	MarketItem []MarketItem        `protobuf:"bytes,1,rep,name=MarketItem,proto3" json:"MarketItem"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMarketItemResponse) Reset()         { *m = QueryAllMarketItemResponse{} }
func (m *QueryAllMarketItemResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllMarketItemResponse) ProtoMessage()    {}
func (*QueryAllMarketItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc4839d34748ebb1, []int{3}
}
func (m *QueryAllMarketItemResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMarketItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMarketItemResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMarketItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMarketItemResponse.Merge(m, src)
}
func (m *QueryAllMarketItemResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMarketItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMarketItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMarketItemResponse proto.InternalMessageInfo

func (m *QueryAllMarketItemResponse) GetMarketItem() []MarketItem {
	if m != nil {
		return m.MarketItem
	}
	return nil
}

func (m *QueryAllMarketItemResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetMarketItemRequest)(nil), "harish551.cosmostore.market.QueryGetMarketItemRequest")
	proto.RegisterType((*QueryGetMarketItemResponse)(nil), "harish551.cosmostore.market.QueryGetMarketItemResponse")
	proto.RegisterType((*QueryAllMarketItemRequest)(nil), "harish551.cosmostore.market.QueryAllMarketItemRequest")
	proto.RegisterType((*QueryAllMarketItemResponse)(nil), "harish551.cosmostore.market.QueryAllMarketItemResponse")
}

func init() { proto.RegisterFile("market/query.proto", fileDescriptor_dc4839d34748ebb1) }

var fileDescriptor_dc4839d34748ebb1 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xbf, 0xae, 0xd3, 0x30,
	0x14, 0xc6, 0xe3, 0x50, 0x18, 0x8c, 0x60, 0xb0, 0x18, 0x4a, 0x40, 0x01, 0x65, 0xa0, 0xfc, 0x93,
	0xad, 0x16, 0x0a, 0x73, 0x3b, 0x50, 0x18, 0x2a, 0x41, 0x46, 0x16, 0xe4, 0xb4, 0x56, 0x6a, 0x35,
	0x89, 0xd3, 0xd8, 0x45, 0x54, 0x88, 0x85, 0x27, 0x40, 0xe2, 0x49, 0x10, 0x3c, 0x44, 0xc7, 0x4a,
	0x2c, 0x4c, 0x08, 0xb5, 0xbc, 0x00, 0x6f, 0x80, 0x12, 0xfb, 0xde, 0xa4, 0xf7, 0xa6, 0xbd, 0xbd,
	0xba, 0x53, 0x2c, 0xe7, 0x7c, 0xdf, 0xf9, 0x7d, 0xc7, 0x36, 0x44, 0x31, 0xcd, 0xa6, 0x4c, 0x91,
	0xd9, 0x9c, 0x65, 0x0b, 0x9c, 0x66, 0x42, 0x09, 0x74, 0x6b, 0x42, 0x33, 0x2e, 0x27, 0xdd, 0x6e,
	0x1b, 0x8f, 0x84, 0x8c, 0x85, 0x54, 0x22, 0x63, 0x58, 0x17, 0x3a, 0xb7, 0x43, 0x21, 0xc2, 0x88,
	0x11, 0x9a, 0x72, 0x42, 0x93, 0x44, 0x28, 0xaa, 0xb8, 0x48, 0xa4, 0x96, 0x3a, 0x0f, 0xb5, 0x80,
	0x04, 0x54, 0x32, 0xed, 0x49, 0xde, 0xb7, 0x03, 0xa6, 0x68, 0x9b, 0xa4, 0x34, 0xe4, 0x49, 0x51,
	0x6c, 0x6a, 0x9b, 0xa6, 0xb5, 0xfe, 0xbc, 0xe3, 0x8a, 0xc5, 0xe6, 0xcf, 0x8d, 0x50, 0x84, 0xa2,
	0x58, 0x92, 0x7c, 0xa5, 0x77, 0xbd, 0x47, 0xf0, 0xe6, 0x9b, 0xdc, 0x71, 0xc0, 0xd4, 0xb0, 0x90,
	0xbc, 0x52, 0x2c, 0xf6, 0xd9, 0x6c, 0xce, 0xa4, 0x42, 0xd7, 0xa1, 0xcd, 0xc7, 0x4d, 0x70, 0x17,
	0xdc, 0x6f, 0xf8, 0x36, 0x1f, 0x7b, 0x53, 0xe8, 0xd4, 0x15, 0xcb, 0x54, 0x24, 0x92, 0xa1, 0x21,
	0x84, 0xe5, 0x6e, 0xa1, 0xba, 0xda, 0x69, 0xe1, 0x3d, 0xb1, 0x71, 0x59, 0xde, 0x6f, 0x2c, 0x7f,
	0xdf, 0xb1, 0xfc, 0x8a, 0x81, 0x37, 0x32, 0x64, 0xbd, 0x28, 0x3a, 0x4d, 0xf6, 0x02, 0xc2, 0x32,
	0xba, 0xe9, 0x75, 0xcf, 0x74, 0xc0, 0xf9, 0x9c, 0xb0, 0x9e, 0xbd, 0x99, 0x13, 0x7e, 0x4d, 0x43,
	0x66, 0xb4, 0x7e, 0x45, 0xe9, 0xfd, 0x00, 0x26, 0xd2, 0x89, 0x2e, 0x3b, 0x22, 0x5d, 0xba, 0x50,
	0x24, 0x34, 0xd8, 0xa2, 0xb6, 0xcd, 0x84, 0xce, 0xa2, 0xd6, 0x2c, 0x55, 0xec, 0xce, 0x3f, 0x1b,
	0x5e, 0x2e, 0xb0, 0xd1, 0x77, 0x50, 0x45, 0x44, 0xcf, 0xf6, 0xc2, 0xed, 0x3c, 0x69, 0xe7, 0xf9,
	0xb9, 0x75, 0x9a, 0xca, 0x7b, 0xfa, 0xf9, 0xe7, 0xdf, 0xaf, 0x36, 0x46, 0x8f, 0xc9, 0xb1, 0x01,
	0x29, 0x0d, 0xc8, 0xd6, 0x6d, 0xcc, 0x85, 0xe4, 0x23, 0x1f, 0x7f, 0x42, 0xdf, 0x00, 0xbc, 0x56,
	0x9a, 0xf5, 0xa2, 0xe8, 0x10, 0xf0, 0xba, 0x8b, 0x70, 0x08, 0x78, 0xed, 0xd1, 0x7a, 0xa4, 0x00,
	0x7f, 0x80, 0x5a, 0x07, 0x82, 0xf7, 0x5f, 0x2e, 0xd7, 0x2e, 0x58, 0xad, 0x5d, 0xf0, 0x67, 0xed,
	0x82, 0x2f, 0x1b, 0xd7, 0x5a, 0x6d, 0x5c, 0xeb, 0xd7, 0xc6, 0xb5, 0xde, 0xe2, 0x90, 0xab, 0xc9,
	0x3c, 0xc0, 0x23, 0x11, 0xd7, 0x9b, 0x7d, 0x38, 0xb2, 0x53, 0x8b, 0x94, 0xc9, 0xe0, 0x4a, 0xf1,
	0xf4, 0x9e, 0xfc, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xee, 0x3e, 0x26, 0x27, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a marketItem by id.
	MarketItem(ctx context.Context, in *QueryGetMarketItemRequest, opts ...grpc.CallOption) (*QueryGetMarketItemResponse, error)
	// Queries a list of marketItem items.
	MarketItemAll(ctx context.Context, in *QueryAllMarketItemRequest, opts ...grpc.CallOption) (*QueryAllMarketItemResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) MarketItem(ctx context.Context, in *QueryGetMarketItemRequest, opts ...grpc.CallOption) (*QueryGetMarketItemResponse, error) {
	out := new(QueryGetMarketItemResponse)
	err := c.cc.Invoke(ctx, "/harish551.cosmostore.market.Query/MarketItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MarketItemAll(ctx context.Context, in *QueryAllMarketItemRequest, opts ...grpc.CallOption) (*QueryAllMarketItemResponse, error) {
	out := new(QueryAllMarketItemResponse)
	err := c.cc.Invoke(ctx, "/harish551.cosmostore.market.Query/MarketItemAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a marketItem by id.
	MarketItem(context.Context, *QueryGetMarketItemRequest) (*QueryGetMarketItemResponse, error)
	// Queries a list of marketItem items.
	MarketItemAll(context.Context, *QueryAllMarketItemRequest) (*QueryAllMarketItemResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) MarketItem(ctx context.Context, req *QueryGetMarketItemRequest) (*QueryGetMarketItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarketItem not implemented")
}
func (*UnimplementedQueryServer) MarketItemAll(ctx context.Context, req *QueryAllMarketItemRequest) (*QueryAllMarketItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarketItemAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_MarketItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMarketItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MarketItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/harish551.cosmostore.market.Query/MarketItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MarketItem(ctx, req.(*QueryGetMarketItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MarketItemAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllMarketItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MarketItemAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/harish551.cosmostore.market.Query/MarketItemAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MarketItemAll(ctx, req.(*QueryAllMarketItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "harish551.cosmostore.market.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MarketItem",
			Handler:    _Query_MarketItem_Handler,
		},
		{
			MethodName: "MarketItemAll",
			Handler:    _Query_MarketItemAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market/query.proto",
}

func (m *QueryGetMarketItemRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMarketItemRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMarketItemRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMarketItemResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMarketItemResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMarketItemResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MarketItem.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllMarketItemRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMarketItemRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMarketItemRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllMarketItemResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMarketItemResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMarketItemResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.MarketItem) > 0 {
		for iNdEx := len(m.MarketItem) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MarketItem[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetMarketItemRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetMarketItemResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MarketItem.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllMarketItemRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllMarketItemResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MarketItem) > 0 {
		for _, e := range m.MarketItem {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetMarketItemRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMarketItemRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMarketItemRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMarketItemResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMarketItemResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMarketItemResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketItem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MarketItem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMarketItemRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMarketItemRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMarketItemRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMarketItemResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMarketItemResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMarketItemResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketItem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarketItem = append(m.MarketItem, MarketItem{})
			if err := m.MarketItem[len(m.MarketItem)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
